### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'duration')

### ISSUE THREAD

**Issue by Silvest89** [estruyf/playwright-github-actions-reporter#8]
I guess since you now don't have any results that the duration is gone as well :P
```
Error in reporter TypeError: Cannot read properties of undefined (reading 'duration')
    at getHtmlTable (/__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/utils/getHtmlTable.js:32:36)
    at GitHubAction.<anonymous> (/__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/index.js:110:77)
    at Generator.next (<anonymous>)
    at /__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/index.js:31:71
    at new Promise (<anonymous>)
    at __awaiter (/__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/index.js:27:12)
    at GitHubAction.onEnd (/__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/index.js:56:16)
    at ReporterV2Wrapper.onEnd (/__w/frontend/frontend/node_modules/playwright/lib/reporters/reporterV2.js:[9](https://github.com/shiftbase-com/frontend/actions/runs/8104411731/job/22151075829#step:5:10)1:165)
    at /__w/frontend/frontend/node_modules/playwright/lib/reporters/multiplexer.js:51:56
    at wrapAsync (/__w/frontend/frontend/node_modules/playwright/lib/reporters/multiplexer.js:79:18)
    at Multiplexer.onEnd (/__w/frontend/frontend/node_modules/playwright/lib/reporters/multiplexer.js:51:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at InternalReporter.onEnd (/__w/frontend/frontend/node_modules/playwright/lib/reporters/internalReporter.js:69:[12](https://github.com/shiftbase-com/frontend/actions/runs/8104411731/job/22151075829#step:5:13))
    at Runner.runAllTests (/__w/frontend/frontend/node_modules/playwright/lib/runner/runner.js:77:28)
    at runTests (/__w/frontend/frontend/node_modules/playwright/lib/cli.js:[13](https://github.com/shiftbase-com/frontend/actions/runs/8104411731/job/22151075829#step:5:14)2:93)
    at t.<anonymous> (/__w/frontend/frontend/node_modules/playwright/lib/cli.js:42:7)
```

**Comment by estruyf** [comment]
Thanks @Silvest89, I've added an extra check. Please verify if it works in the latest beta.

**Comment by Silvest89** [comment]
@estruyf 
Now it turned into since results is used there as well. I expect it to break everywhere where results is used :P
```
Error in reporter TypeError: Cannot read properties of undefined (reading 'status')
    at /__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/utils/getTestStatusIcon.js:7:27
    at Array.map (<anonymous>)
    at getTestStatusIcon (/__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/utils/getTestStatusIcon.js:5:32)
    at GitHubAction.<anonymous> (/__w/frontend/frontend/node_modules/@estruyf/github-actions-reporter/dist/index.js:112:[9](https://github.com/shiftbase-com/frontend/actions/runs/8138112183/job/22238714914#step:5:10)4)
    at Generator.next (<anonymous>)
```

**Comment by estruyf** [comment]
A new beta release has been published. I've also added some unit tests to test the behaviour on different result inputs.

**Comment by Silvest89** [comment]
@estruyf 
That seems to have fixed it. I see the summary again :P

**Comment by estruyf** [comment]
Thanks! I'll release v1.5.1
